In [1]:
import pandas as pd

In [2]:
import os
from os import listdir
from os.path import isfile, join, dirname, basename

In [3]:
from matplotlib import pyplot as plt
import numpy as np
import math

In [4]:
from analysis_utils import collect_cv_metrics, map_groups

In [5]:
def load_results(base_dir):
    experiments = [ join(base_dir, f.name) for f in os.scandir(base_dir) if f.is_dir() ]
    results = collect_cv_metrics(experiments)
    return results

In [6]:
def save_experminets(mil_df, task, prefix, save_dir):
    
    mil_df.to_csv(join(save_dir, f'{prefix}.csv'))
    metrics = mil_df.Metrics.unique()
    mil_df['group'] = mil_df.experiment.map(map_groups)

    for m in metrics:
        mil_df_m= mil_df[mil_df.Metrics ==m]
        mil_df_m = mil_df_m.groupby(['experiment', 'group'])['model'].agg(['mean', 'std']).reset_index()
        mil_df_m.to_csv(join(save_dir, f'{m}_{prefix}.csv'))

## Chemo

In [7]:
save_dir ='./metrics/brca_full_chemo'
task ='chemo'
base_dir = '/home/haitham/mnt/exp/__output_clean/brca_full/chemo'
os.makedirs(save_dir, exist_ok=True)
results= load_results(base_dir)
mil_df = results["mil"]
vote_df = results["vote"]
avg_df = results["avg"]

Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/gf-6L-30M-i2048_finetune_2epoch_vote_freez2
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/gf-6L-30M-i2048_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/Geneformer-V2-104M_finetune
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/gf-6L-30M-i2048_all_cells_donor_id
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/gf-6L-30M-i2048_finetune_10epoch
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/gf-6L-30M-i2048_finetune_freez2
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/gf-6L-30M-i2048_finetune_2epoch
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/Geneformer-V2-104M_finetune_freez9
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/Geneformer-V2-104M_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/gf-6L-30M-i2048_finetune
Missing files in /home/jupyter/mnt/__output_clean/brca_full/chemo/gf-6L-30M-i2048_finetune_2epoch_vote

In [8]:
mil_df

       Metrics     model    fold                   experiment
0          AUC  0.857143  fold_1  Geneformer-V2-104M_CLcancer
1        AUPRC  0.500000  fold_1  Geneformer-V2-104M_CLcancer
2           F1  0.466667  fold_1  Geneformer-V2-104M_CLcancer
3     Accuracy  0.875000  fold_1  Geneformer-V2-104M_CLcancer
4    Precision  0.437500  fold_1  Geneformer-V2-104M_CLcancer
..         ...       ...     ...                          ...
355      AUPRC  0.500000  fold_5                         scvi
356         F1  0.416667  fold_5                         scvi
357   Accuracy  0.714286  fold_5                         scvi
358  Precision  0.416667  fold_5                         scvi
359     Recall  0.416667  fold_5                         scvi

[360 rows x 4 columns]

In [9]:
idx = mil_df.experiment.str.contains('full')
mil_df = mil_df[~idx]

idx = vote_df.experiment.str.contains('full')
vote_df = vote_df[~idx]

idx = avg_df.experiment.str.contains('full')
avg_df = avg_df[~idx]

In [10]:
idx = mil_df.experiment.str.contains('test')
mil_df = mil_df[~idx]

idx = vote_df.experiment.str.contains('test')
vote_df = vote_df[~idx]

idx = avg_df.experiment.str.contains('test')
avg_df = avg_df[~idx]

In [11]:
save_experminets(mil_df, task, 'mil', save_dir)
save_experminets(vote_df, task, 'vote', save_dir)
save_experminets(avg_df, task, 'avg', save_dir)

## Pre-Post

In [12]:
save_dir ='./metrics/brca_full_pre_post'
task ='pre_post'
base_dir = '/home/jupyter/mnt/__output_clean/brca_full/pre_post'
os.makedirs(save_dir, exist_ok=True)
results= load_results(base_dir)
mil_df = results["mil"]
vote_df = results["vote"]
avg_df = results["avg"]

Missing files in /home/jupyter/mnt/__output_clean/brca_full/pre_post/gf-6L-30M-i2048_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/brca_full/pre_post/Geneformer-V2-104M_finetune
Missing files in /home/jupyter/mnt/__output_clean/brca_full/pre_post/gf-6L-30M-i2048_finetune_freez2
Missing files in /home/jupyter/mnt/__output_clean/brca_full/pre_post/Geneformer-V2-104M_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/brca_full/pre_post/gf-6L-30M-i2048_finetune

In [13]:
vote_df

       Metrics     model    fold                   experiment
0          AUC  1.000000  fold_1  Geneformer-V2-104M_CLcancer
1        AUPRC  1.000000  fold_1  Geneformer-V2-104M_CLcancer
2           F1  0.845238  fold_1  Geneformer-V2-104M_CLcancer
3     Accuracy  0.846154  fold_1  Geneformer-V2-104M_CLcancer
4    Precision  0.875000  fold_1  Geneformer-V2-104M_CLcancer
..         ...       ...     ...                          ...
385      AUPRC  0.976190  fold_5                         scvi
386         F1  0.833333  fold_5                         scvi
387   Accuracy  0.833333  fold_5                         scvi
388  Precision  0.833333  fold_5                         scvi
389     Recall  0.833333  fold_5                         scvi

[390 rows x 4 columns]

In [14]:
df = vote_df[vote_df['Metrics']=='AUPRC']
df.groupby(['experiment'])['model'].agg(['mean', 'std']).reset_index()

                         experiment      mean           std
0                Geneformer-V2-104M  0.975000  2.711802e-02
1       Geneformer-V2-104M_CLcancer  0.983333  3.726780e-02
2                Geneformer-V2-316M  0.981349  2.577838e-02
3                           cellplm  0.852665  6.937475e-02
4                   gf-6L-30M-i2048  0.933023  7.670428e-02
5   gf-6L-30M-i2048_finetune_freez2  1.000000  1.241267e-16
6                               hvg  1.000000  1.241267e-16
7                               pca  1.000000  1.241267e-16
8                      scfoundation  1.000000  1.241267e-16
9                             scgpt  0.930285  1.338170e-01
10                     scgpt_cancer  0.974531  4.484172e-02
11                      scimilarity  0.983333  3.726780e-02
12                             scvi  0.995238  1.064794e-02

In [15]:
avg_df

       Metrics     model    fold                   experiment
0          AUC  0.976190  fold_1  Geneformer-V2-104M_CLcancer
1        AUPRC  0.982143  fold_1  Geneformer-V2-104M_CLcancer
2           F1  0.845238  fold_1  Geneformer-V2-104M_CLcancer
3     Accuracy  0.846154  fold_1  Geneformer-V2-104M_CLcancer
4    Precision  0.875000  fold_1  Geneformer-V2-104M_CLcancer
..         ...       ...     ...                          ...
415      AUPRC  0.976190  fold_5                         scvi
416         F1  0.833333  fold_5                         scvi
417   Accuracy  0.833333  fold_5                         scvi
418  Precision  0.833333  fold_5                         scvi
419     Recall  0.833333  fold_5                         scvi

[420 rows x 4 columns]

In [16]:
# save_experminets(mil_df, avg_df, task, save_dir)
save_experminets(mil_df, task, 'mil', save_dir)
save_experminets(vote_df, task, 'vote', save_dir)
save_experminets(avg_df, task, 'avg', save_dir)

## outcome

In [17]:
save_dir ='./metrics/brca_full_outcome'
task ='outcome'
base_dir = '/home/jupyter/mnt/__output_clean/brca_full/outcome'
os.makedirs(save_dir, exist_ok=True)
results= load_results(base_dir)
mil_df = results["mil"]
vote_df = results["vote"]
avg_df = results["avg"]

Missing files in /home/jupyter/mnt/__output_clean/brca_full/outcome/gf-6L-30M-i2048_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/brca_full/outcome/Geneformer-V2-104M_finetune
Missing files in /home/jupyter/mnt/__output_clean/brca_full/outcome/gf-6L-30M-i2048_finetune_freez2
Missing files in /home/jupyter/mnt/__output_clean/brca_full/outcome/Geneformer-V2-104M_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/brca_full/outcome/gf-6L-30M-i2048_finetune

In [18]:
# vote_df

In [19]:
df = vote_df[vote_df['Metrics']=='AUPRC']
df.groupby(['experiment'])['model'].agg(['mean', 'std']).reset_index()

                         experiment      mean       std
0                Geneformer-V2-104M  0.773333  0.234106
1       Geneformer-V2-104M_CLcancer  0.790000  0.234994
2                Geneformer-V2-316M  0.766667  0.245798
3                           cellplm  0.500000  0.282597
4                   gf-6L-30M-i2048  0.806667  0.212655
5          gf-6L-30M-i2048_finetune  0.700000  0.298142
6   gf-6L-30M-i2048_finetune_freez2  0.806667  0.212655
7                               hvg  0.750000  0.343592
8                               pca  0.700000  0.315128
9                      scfoundation  0.723333  0.287615
10                            scgpt  0.756667  0.239096
11                     scgpt_cancer  0.800000  0.217307
12                      scimilarity  0.790000  0.243698
13                             scvi  0.723333  0.287615

In [20]:
save_experminets(mil_df, task, 'mil', save_dir)
save_experminets(vote_df, task, 'vote', save_dir)
save_experminets(avg_df, task, 'avg', save_dir)

## Subtype

In [21]:
save_dir ='./metrics/brca_full_subtype'
task ='subtype'
base_dir = '/home/jupyter/mnt/__output_clean/brca_full/subtype'
os.makedirs(save_dir, exist_ok=True)
results= load_results(base_dir)
mil_df = results["mil"]
vote_df = results["vote"]
avg_df = results["avg"]
# save_experminets(mil_df, avg_df, task, save_dir)

Missing files in /home/jupyter/mnt/__output_clean/brca_full/subtype/gf-6L-30M-i2048_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/brca_full/subtype/Geneformer-V2-104M_finetune
Missing files in /home/jupyter/mnt/__output_clean/brca_full/subtype/gf-6L-30M-i2048_finetune_freez2
Missing files in /home/jupyter/mnt/__output_clean/brca_full/subtype/Geneformer-V2-104M_finetune2
Missing files in /home/jupyter/mnt/__output_clean/brca_full/subtype/Geneformer-V2-104M_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/brca_full/subtype/gf-6L-30M-i2048_finetune

In [22]:
idx = mil_df.experiment.str.contains('tcell')
mil_df = mil_df[~idx]

idx = vote_df.experiment.str.contains('tcell')
vote_df = vote_df[~idx]

idx = avg_df.experiment.str.contains('tcell')
avg_df = avg_df[~idx]

In [23]:
save_experminets(mil_df, task, 'mil', save_dir)
save_experminets(vote_df, task, 'vote', save_dir)
save_experminets(avg_df, task, 'avg', save_dir)

## LUAD1

In [24]:
save_dir ='./metrics/luad1'
task ='luad1'
base_dir = '/home/jupyter/mnt/__output_clean/luad1'
os.makedirs(save_dir, exist_ok=True)
results= load_results(base_dir)
mil_df = results["mil"]
vote_df = results["vote"]
avg_df = results["avg"]
# save_experminets(mil_df, avg_df, task, save_dir)

Missing files in /home/jupyter/mnt/__output_clean/luad1/.ipynb_checkpoints
Missing files in /home/jupyter/mnt/__output_clean/luad1/Geneformer-V2-104M_finetune
Missing files in /home/jupyter/mnt/__output_clean/luad1/Geneformer-V2-104M_finetune_freez2
Missing files in /home/jupyter/mnt/__output_clean/luad1/gf-6L-30M-i2048_finetune_freez2
Missing files in /home/jupyter/mnt/__output_clean/luad1/gf-6L-30M-i2048_finetune
Missing files in /home/jupyter/mnt/__output_clean/luad1/scimilarity_no_batch

In [25]:
save_experminets(mil_df, task, 'mil', save_dir)
save_experminets(vote_df, task, 'vote', save_dir)
save_experminets(avg_df, task, 'avg', save_dir)

In [26]:
save_dir ='./metrics/luad2'
task ='luad2'
base_dir = '/home/jupyter/mnt/__output_clean/luad2'
os.makedirs(save_dir, exist_ok=True)
results= load_results(base_dir)
mil_df = results["mil"]
vote_df = results["vote"]
avg_df = results["avg"]
# save_experminets(mil_df, avg_df, task, save_dir)

Missing files in /home/jupyter/mnt/__output_clean/luad2/.ipynb_checkpoints
Missing files in /home/jupyter/mnt/__output_clean/luad2/gf-6L-30M-i2048_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/luad2/Geneformer-V2-104M_finetune
Missing files in /home/jupyter/mnt/__output_clean/luad2/Geneformer-V2-104M_finetune_freez2
Missing files in /home/jupyter/mnt/__output_clean/luad2/gf-6L-30M-i2048_finetune_freez2
Missing files in /home/jupyter/mnt/__output_clean/luad2/Geneformer-V2-104M_finetune_original
Missing files in /home/jupyter/mnt/__output_clean/luad2/gf-6L-30M-i2048_finetune

In [27]:
save_experminets(mil_df, task, 'mil', save_dir)
save_experminets(vote_df, task, 'vote', save_dir)
save_experminets(avg_df, task, 'avg', save_dir)